### ISSUE TITLE
Link has excess ")"

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports.com#57]
On https://ubports.com/page/frequently-asked-questions in the Android answer, the link has an excess ) at the end.

**Comment by PeterNerlich** [comment]
I see, my reporting to the UBFR group didn't reach the web team. I'm quickly gonna paste my message *(from 2017-12-26T20:13 UTC)*, because it reports a bit more than that paranthesis but I don't think it's work filing a new issue (maybe rename this to `fix minor issues`)

`[CRITICAL]` Wrong link in FAQ (https://ubports.com/page/frequently-asked-questions) in *Will you port to my device, which is not currently in the core devices or legacy devices list?*
`...this guide ( https://......-Information) might be...`
*1)* unneccessary space before link, *2)* link includes the `)` at the end, not only spans the text, but the reference is mutated as well
Anyone with access, please fix as soon as convenient

`[EDIT]` after scanning the rest of the page for similar errors
*How do you "say" UBports? How do you say Ubuntu?*: unneccessary space after link
*Does Ubuntu Touch support Android apps?*: Same misplaced space mutated link problem as above
